### ISSUE TITLE
Setting Styles for the `<Text />` Component to Support Themes

### ISSUE THREAD

**Issue by Andresbl123** [selsa-inube/design-system-web#143]
Adjusting Styles for the  `<Text />` Component to Support Themes
Currently, components that interact with the  `<Text />` component have problems receiving the prop theme provided by styled-components. This is due to a logic error in the implementation of the styles within the **@inubekit/text** package. The problem is that the props are not being properly destructured in the `<StyledText />` component, specifically in the `font-family` property.

![image](https://github.com/user-attachments/assets/407d9780-b77a-40d4-b6af-e66b97eb825b)
![image](https://github.com/user-attachments/assets/c50d036b-32b3-445a-93f9-519c4fd97b0c)

**Comment by cmarin001** [comment]
This issue was solve on IDS1773
