### ISSUE TITLE
Fieldset component does not have attributes for type and font size

### ISSUE THREAD

**Issue by CristianRojas-47** [selsa-inube/design-system-web#151]
The Fieldset component does not allow selecting the font type and size, which is necessary for interface design, especially due to screen size changes.

Mobile:
![image](https://github.com/user-attachments/assets/c5ea637f-7cb3-4aff-8245-0eac00ed08cb)

Desktop and Tablet:
![image](https://github.com/user-attachments/assets/08b7cf83-5a66-44cb-a604-bc320690f549)

**Comment by wfercanas** [comment]
Accepted and added to design-system backlog.

**Comment by CristianRojas-47** [comment]
- The fieldset is not closing the edge when starting the legend.
- The fieldset should be adjusted so that it does not have a min-height.

![image](https://github.com/user-attachments/assets/52b02ca4-f681-4b7f-b503-ccc9f720c50d)

**Comment by CristianRojas-47** [comment]
The bug was fixed in **v0.24.6**
