### ISSUE TITLE
Adjustments to be made by the Assisted component

### ISSUE THREAD

**Issue by CristianRojas-47** [selsa-inube/design-system-web#158]
1. When the size attribute is defined as small, the component does not have the expected size for small screens. Upon reviewing it, this is because the component itself measures 312 px without including the padding, which should be included. Additionally, in the definition of the 'back' and 'next' icons, they are not the same, causing them to appear different.

![image](https://github.com/user-attachments/assets/7b296f54-3cda-4a20-a49f-db431a7c1701)

2. The 'next' button cannot be set to 'disabled'; therefore, the validations that are performed and are necessary at each step can be bypassed.

![image](https://github.com/user-attachments/assets/764857ab-0cb8-4ee2-bcd1-d07906a1ff72)

3. When the screen is for desktop, the label is not aligned with the number that identifies the step. The container for the number could be vertically centered.

![image](https://github.com/user-attachments/assets/b1c7bc70-afb6-44b2-9df0-6f7e91372374)

**Comment by wfercanas** [comment]
@CristianRojas-47 , se hacen las correcciones en la v6.0.0 del Assisted. Por favor validar y si está bien cerrar la issue.

**Comment by CristianRojas-47** [comment]
The issue was fixed in **v7.0.0**
