### ISSUE TITLE
Adjust the design of the Flag component

### ISSUE THREAD

**Issue by CristianRojas-47** [selsa-inube/design-system-web#159]
Adjust the design of the Flag component in case the description is extensive.

**Extensive text:** The progress bar is outside of the box.

![image](https://github.com/user-attachments/assets/819c2344-0f8f-4455-8913-a498de96e0b7)

**Short text:** The behavior of the component is correct.
![image](https://github.com/user-attachments/assets/94cfb64c-d738-410c-8497-eae3a1bf60ec)

**Comment by CristianRojas-47** [comment]
@wfercanas Tengo una duda: la descripción debe tener el límite de 45 caracteres.
![image](https://github.com/user-attachments/assets/b7190151-a116-414f-bf76-4063bb2adc6e)

De ser así, esta es la función que modifica la descripción recibida.
![image](https://github.com/user-attachments/assets/4bd6a713-62a8-427f-a3bd-ab647e699376)

**Comment by wfercanas** [comment]
@CristianRojas-47 , se ajustó para que tenga 80ch máximo la longitud. Si el mensaje toma más de esa longitud, ya habría que evaluar el mensaje específico para sintetizar.

**Comment by CristianRojas-47** [comment]
The bug was fixed in **v7.1.0**
