### ISSUE TITLE
Adjust attribute in Nav component

### ISSUE THREAD

**Issue by CristianRojas-47** [selsa-inube/design-system-web#160]
The logoutPath attribute currently accepts only a string. We need it to accept a function in order to log out, as we use a library for authentication.

**Comment by wfercanas** [comment]
Se asigna issue para extender props tanto de Nav como de FullscreenNav.

Así como estos componentes reciben una prop "navigation" donde se pueden relacionar todos los links a los que se puede navegar usando el nav/fullscreen-nav, se agregará también una prop "actions" que será una lista de acciones que se renderizarán luego del divider de las opciones de "navigation".

A diferencia de un link en navigation que recibe un path para navegar, estas actions recibirán una función que se ejecutará on click.

**Comment by wfercanas** [comment]
@CristianRojas-47 por favor validar si esta issue ya fue completada y de ser así, cerrarla.

**Comment by CristianRojas-47** [comment]
La incidencia ya se encuentra ajustada en la versión **v5.0.1**.
