### ISSUE TITLE
Add a Scroll-Y to the Nav Component

### ISSUE THREAD

**Issue by CristianRojas-47** [selsa-inube/design-system-web#168]
Due to the fact that there are several options currently in development that are not visible in production, it is necessary to add a scroll to properly view all the options.

![imagen](https://github.com/user-attachments/assets/99f886a0-94f2-444d-a21f-f7dcace54739)

**Comment by wfercanas** [comment]
Hola @CristianRojas-47.
Se hace el ajuste del scroll-y en el nav y se publica con la versión 5.3.1. Por favor validar su correcto funcionamiento y en caso afirmativo cerrar la issue.

**Comment by CristianRojas-47** [comment]
La incidencia ya se encuentra ajustada en la versión **v5.3.1**
