### ISSUE TITLE
Inconsistent `<BreadcrumbLink/>` Appearance Based on Condition Fulfillment

### ISSUE THREAD

**Issue by cmarin001** [selsa-inube/design-system-web#64]
We have detected an issue within the `<Breadcrumbs/>` component. The behavior functions correctly under the following condition: `const maxCrumbs = isDesktop ? 5 : 3; if (crumbs.length > maxCrumbs)`. In this scenario, the last `<BreadcrumbLink/>` is correctly set to a 'dark' appearance, as shown in this image
![image](https://github.com/selsa-inube/design-system-web/assets/45011420/2871cf4a-009b-4215-baf1-5717e51b5edc)

However, when this condition is not met, the entire `<BreadcrumbLink/>` defaults to a 'gray' appearance, which is not the intended behavior, as illustrated in this image: 
![image](https://github.com/selsa-inube/design-system-web/assets/45011420/dbb390a4-b721-4642-b013-212637f5499e)

**Comment by Andresbl123** [comment]
In process

**Comment by Andresbl123** [comment]
awaiting release

**Comment by Andresbl123** [comment]
released

**Comment by cmarin001** [comment]
this issue was solved in a `<Breadcrumb/>`
