### ISSUE TITLE
 Enhancement of `<Nav/>` Component for Background Color Compatibility

### ISSUE THREAD

**Issue by cmarin001** [selsa-inube/design-system-web#68]
The `<Nav/>` component presently lacks the capability to handle a background color attribute. It is essential to update this component so that it aligns with our Figma design specifications. Specifically, the background color property should be integrated and linked to the 'surface-token nav' to ensure consistent and accurate styling across our application. This enhancement will enable better design conformity and visual appeal as per our design guidelines.

![image](https://github.com/selsa-inube/design-system-web/assets/45011420/6bc71e0d-8d38-4591-9775-36456d2544a9)

**Comment by Andresbl123** [comment]
in process

**Comment by cmarin001** [comment]
it was solve on former version of nav-component
